# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64)),
                ('phonenumber', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=60)),
                ('account_type', models.CharField(max_length=30)),
                ('created_time', models.DateTimeField()),
                ('last_modified_time', models.DateTimeField()),
                ('stop', models.SmallIntegerField(choices=[(0, 'ACTIVE'), (1, 'STOPPED')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyInfo',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='star.Account')),
                ('verifymsg', models.CharField(max_length=200)),
                ('valid_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('verify_type', models.CharField(max_length=30)),
            ],
        ),
    ]
